"""Add title_relevane and abstract_relevance to SearchResultTitleAbstract table

Revision ID: 0a28853081d5
Revises: ee1b2f26ad19
Create Date: 2024-10-05 14:41:40.962497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a28853081d5'
down_revision: Union[str, None] = 'ee1b2f26ad19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results_title_abstract', sa.Column('title_relevance', sa.String(), nullable=True))
    op.add_column('search_results_title_abstract', sa.Column('abstract_relevance', sa.String(), nullable=True))
    op.drop_column('search_results_title_abstract', 'manual_title_relevance')
    op.drop_column('search_results_title_abstract', 'manual_overall_relevance')
    op.drop_column('search_results_title_abstract', 'manual_abstract_relevance')
    op.drop_column('search_results_title_abstract', 'ai_abstract_relevance')
    op.drop_column('search_results_title_abstract', 'ai_title_relevance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results_title_abstract', sa.Column('ai_title_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results_title_abstract', sa.Column('ai_abstract_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results_title_abstract', sa.Column('manual_abstract_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results_title_abstract', sa.Column('manual_overall_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results_title_abstract', sa.Column('manual_title_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('search_results_title_abstract', 'abstract_relevance')
    op.drop_column('search_results_title_abstract', 'title_relevance')
    # ### end Alembic commands ###
