"""temp migration3

Revision ID: 358411badf17
Revises: a13d0267d084
Create Date: 2024-09-21 16:56:58.085072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358411badf17'
down_revision: Union[str, None] = 'a13d0267d084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('tempfield', sa.String(), nullable=True))
    op.drop_column('search_results', 'manual_full_text_relevance')
    op.drop_column('search_results', 'ai_full_text_relevance')
    op.drop_column('search_results', 'fullText')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('fullText', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results', sa.Column('ai_full_text_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results', sa.Column('manual_full_text_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('search_results', 'tempfield')
    # ### end Alembic commands ###
