"""Store papers as JSON in current_search_result table

Revision ID: 447a31f25e30
Revises: 6dfb772c2602
Create Date: 2024-09-24 03:56:55.585466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447a31f25e30'
down_revision: Union[str, None] = '6dfb772c2602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_search_result', sa.Column('papers', sa.JSON(), nullable=True))
    op.drop_column('current_search_result', 'title')
    op.drop_column('current_search_result', 'paperId')
    op.drop_column('current_search_result', 'url')
    op.drop_column('current_search_result', 'year')
    op.drop_column('current_search_result', 'abstract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_search_result', sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('current_search_result', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('current_search_result', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('current_search_result', sa.Column('paperId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('current_search_result', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('current_search_result', 'papers')
    # ### end Alembic commands ###
