"""adding visualisation for reranked title outputs

Revision ID: 54f62d1542f2
Revises: 447a31f25e30
Create Date: 2024-10-01 13:34:55.949055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f62d1542f2'
down_revision: Union[str, None] = '447a31f25e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualise_reranked_title',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualise_reranked_title')
    # ### end Alembic commands ###
