"""Remove tempfield

Revision ID: e5037fa34393
Revises: 358411badf17
Create Date: 2024-09-21 17:29:07.006954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5037fa34393'
down_revision: Union[str, None] = '358411badf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_results', 'tempfield')
    op.drop_column('search_results', 'ai_overall_relevance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('ai_overall_relevance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_results', sa.Column('tempfield', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
