"""added a new Research Question Table

Revision ID: 5e5fbd29e63d
Revises: 4fc759eb67d7
Create Date: 2024-09-22 12:20:27.542997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5fbd29e63d'
down_revision: Union[str, None] = '4fc759eb67d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
