"""RQ Table Added

Revision ID: f2f78a7879ba
Revises: 89ba206524c2
Create Date: 2024-09-22 12:36:03.546168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f78a7879ba'
down_revision: Union[str, None] = '89ba206524c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_questions',
    sa.Column('research_question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=True),
    sa.Column('relevant_papers', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.search_id'], ),
    sa.PrimaryKeyConstraint('research_question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_questions')
    # ### end Alembic commands ###
