name: CI/CD for FastAPI Server

on:
  push:
    branches:
      - development
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 Instance
        run: |
          if [ "${{ github.ref }}" == "refs/heads/development" ]; then
            EC2_INSTANCE="${{ secrets.DEV_EC2_HOST }}"
            BRANCH="development"
          elif [ "${{ github.ref }}" == "refs/heads/production" ]; then
            EC2_INSTANCE="${{ secrets.PROD_EC2_HOST }}"
            BRANCH="production"
          fi

          ssh -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE << 'EOF'
          # Set the branch name
          cd ForYourResearch
          git branch

          # Ensure the correct branch is checked out
          git fetch origin
          git checkout $BRANCH
          git pull origin $BRANCH

          # Verify the branch
          echo "Current branch is: $(git branch --show-current)"

          # Reset hard to ensure no stale files
          git reset --hard origin/$BRANCH

          # Set up virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Go into the app directory to install requirements
          cd app
          pip install -r requirements.txt
          cd ..

          # Start the FastAPI server
        EOF
