name: CI/CD for FastAPI Server

on:
  push:
    branches:
      - development
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 Instance
        run: |
          if [ "${{ github.ref }}" == "refs/heads/development" ]; then
            EC2_INSTANCE="${{ secrets.DEV_EC2_HOST }}"
          elif [ "${{ github.ref }}" == "refs/heads/production" ]; then
            EC2_INSTANCE="${{ secrets.PROD_EC2_HOST }}"
          fi

          ssh -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE << 'EOF'
            # Start Caddy server
            sudo caddy start

            # Navigate to the project directory
            cd ForYourResearch

            # Pull the latest code
            git pull origin ${{ github.ref }}

         

            # Create and activate a virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Install requirements
            pip install -r requirements.txt

            # Kill the existing FastAPI server
            sudo pkill -f "my_uvicorn_app"

            # Start the FastAPI server
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &

          EOF
